[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Kerwinson", email = "joshua.hall2020@outlook.com"},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

